### ISSUE TITLE
Natives not correctly resolving

### ISSUE THREAD

**Issue by nelsonxb** [nelsonxb/GraphPaperRaceGame#11]
Natives in mac aren't resolving correctly (last I saw, based off of @RSteyn's experience). Gonna need some way of fixing that in Gradle.

This causes a crash almost immediately upon opening the game.

**Comment by nelsonxb** [comment]
There is a temporary manual fix you can try if this is affecting you:
1. Go to where the natives are stored (by default: `{HOME}/Library/Application Support/gprg/natives`, note that `{HOME}/Library` is hidden in Finder)
2. Rename `liblwjgl.jnilib` to `liblwjgl.dylib`
3. Run the game again

Let us know here if this issue is still affecting you.

**Comment by RSteyn** [comment]
I probably should have closed this a way ago.  This no longer appears to be an issue.

**Comment by nelsonxb** [comment]
Are you _absolutely certain_ - did you change the filename back?

**Comment by RSteyn** [comment]
Nevermind, I was wrong.

**Comment by nelsonxb** [comment]
Might be fixed in 0ff2f95dc26b19f31fe7340fee01a77df3acdc1f

@RSteyn Please contact me to help test

**Comment by nelsonxb** [comment]
Fixed a12c4b63779ea66b7d009371200dd86be60fb678
