### ISSUE TITLE
More clear indication of what player is currently active

### ISSUE THREAD

**Issue by nelsonxb** [nelsonxb/GraphPaperRaceGame#17]
There needs to be some clearer rendered indication of whose turn it is currently, possibly also whose turn is next.

**Comment by RSteyn** [comment]
This may have been dealt with in the changes I introduced in commit beb00d0dc586de0c1cda1dcb8c7d6413e19c8d4a?

**Comment by nelsonxb** [comment]
Not quite the way I'd like - maybe the current player is rendered differently?

**Comment by RSteyn** [comment]
Active player now emphasised by halo.  Also introduced lines between prior locations.  Commit 9bb36127b455bf3200dc88acd89b967df57c425f
