### ISSUE TITLE
Better display of what options are available for the current turn

### ISSUE THREAD

**Issue by nelsonxb** [nelsonxb/GraphPaperRaceGame#18]
Currently, a circle is rendered at the next principal point to indicate where the players can move. It needs to be clearer exactly what options are available, perhaps a dot on each of the possible next turn points.

I think that the currently selected point should also have a slightly different shape (perhaps a smaller, filled circle?).

**Comment by RSteyn** [comment]
Done, though it can, as always, be tweaked at a later time.  Commit beb00d0dc586de0c1cda1dcb8c7d6413e19c8d4a
