### ISSUE TITLE
Decide on GUI system

### ISSUE THREAD

**Issue by nelsonxb** [nelsonxb/GraphPaperRaceGame#20]
We need a GUI (for menus etc.) soon. But, before we get one, we need to decide on how the GUI will be created.

There are a number of options ([some found on LWJGL wiki](http://wiki.lwjgl.org/index.php?title=Game_Engines_and_Libraries_Using_LWJGL#GUI_Libraries)):
- [Nifty GUI](https://github.com/void256/nifty-gui) (works off of XML)
- [Gooei](https://code.google.com/p/gooei/) (appears to be **_very_** poorly documented)
- [FengGUI](http://www.fenggui.org/doku.php) (appears to be a hard-coding system)
- Create our own (it would work _exactly_ how we want it, based off of slick, but would take time)

**Comment by nelsonxb** [comment]
NiftyGUI appears to be really difficult to import into the project.

I haven't found any form of documentation at all on Gooei.

FengGUI appears to be stale.

The only other library I can seem to find is the other one listed on the LWJGL wiki, TWL, but from what I can see (which isn't much), it doesn't have any kind of special support for Slick2d. It also looks to be stale.

Unless you have made some other magical discovery, I'm seeing two options:
- I go waaaaaay out of my way to get Nifty working
- We both go waaaaaay out of our ways to create our own system
  - Benefit of this: It will work exactly as we want it to, and will do so right out of the box.

**Comment by RSteyn** [comment]
Creating our own.  Decided.

**Comment by nelsonxb** [comment]
See [NelsonCrosby/QuickSlickUI](https://github.com/NelsonCrosby/QuickSlickUI)
