### ISSUE TITLE
Acceleration-based movement

### ISSUE THREAD

**Issue by nelsonxb** [nelsonxb/GraphPaperRaceGame#5]
Currently, only trivial cell-by-cell movement is implemented.

A player has to choose the next move based on the velocity of the previous move.

Details on movement are described on [the Racetrack Wikipedia page](http://en.wikipedia.org/wiki/Racetrack_%28game%29#The_moves).

**Comment by nelsonxb** [comment]
We also need to view the current acceleration

**Comment by RSteyn** [comment]
Made progress, implemented basic acceleration (unviewable).  Commit fcf96dac044b6428fc829d259a0078ac9d1baef6

**Comment by nelsonxb** [comment]
5f55d76e4b012ce04915d7350d8c4eb518e13aff
