### ISSUE TITLE
Basic track selection

### ISSUE THREAD

**Issue by nelsonxb** [nelsonxb/GraphPaperRaceGame#6]
Initially, we just need basic track selection - the options could possibly even be hard-coded - just some way to choose between a few default tracks.

**Comment by RSteyn** [comment]
Done, but the most bare-bones thing imaginable.  I got bored.  Completed with commit 38051ec92bca7b591350cb67ea89884712c69113

**Comment by nelsonxb** [comment]
Damn.

Honestly, I actually didn't like what I had already done (not sure why). I'd want to design the whole UI API co-operatively (or, perhaps, in a separate project). Gonna push that part back a bit.
